# Generated by Django 5.0.6 on 2024-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='orderd_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
