# Generated by Django 5.0.6 on 2024-07-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cdesc', models.TextField()),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='media/image')),
            ],
        ),
    ]
